### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by jdamerow**

### CODE REVIEW

**Review by rlskoeser — COMMENTED** [review]
Should we add a note to the readme about the license?

**Comment by ColeDCrawford** [comment]
I think you can also add it under the repo settings, though that's only helpful if you're on Github.

**Comment by rlskoeser** [comment]
> I think you can also add it under the repo settings, though that's only helpful if you're on Github.

I think that should be picked up automatically once we merge

**Comment by rlskoeser** [comment]
@jdamerow I added a note to the readme about the license. If you think it looks ok, let's merge this!

**Review by rlskoeser — APPROVED** [review]

**Pull request merged**
